# Generated by Django 5.0.3 on 2024-08-31 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0003_remove_workshop_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='room',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='forumcategory',
            old_name='Categoryname',
            new_name='name',
        ),
    
        migrations.RemoveField(
            model_name='forumpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='mental_health_app.forumcategory'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mental_health_app.forumtopic'),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
