# Generated by Django 5.1 on 2024-09-05 09:39

import django.db.models.deletion
import mental_health_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0004_forumtopic_remove_chatmessage_room_delete_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(default=mental_health_app.models.get_general_room_id, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mental_health_app.chatroom'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_health_app.chatmessage')),
            ],
        ),
    ]
