# Generated by Django 5.0.3 on 2024-10-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0005_chatroom_rename_message_chatmessage_text_and_more'),
    ]

  