# Generated by Django 5.0.3 on 2024-10-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health_app', '0006_remove_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
